name: bookly
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.2.0
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  font_awesome_flutter: ^10.2.1
  get_it: ^7.2.0
  go_router: ^5.2.4
  google_fonts: ^6.2.1
  url_launcher: ^6.1.7
  device_preview: ^1.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/screenshots/
    - assets/images/Logo.svg
    - assets/images/test_name_jar.jpg
    - assets/icons/search.svg


